stages:
  - build
  
variables:
  SLN_NAME: "BicycleCalculatorWPF"
  
job:
  stage: build
  script:
    - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%CI_PROJECT_DIR%/%SLN_NAME%.sln"
  artifacts:
    paths:
      - "%SLN_NAME%/bin/Release/*.exe"
      - "%SLN_NAME%/bin/Release/zh-Hans/*.*"
      - "%SLN_NAME%/bin/Release/*.dll"
      - "%SLN_NAME%/bin/Release/DLL/*.dll"